// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTvT_UAf_wGiY6mTjN_DvJg4x562ZlN9I',
    appId: '1:776876278367:web:fd6d65007e69df13cf51ea',
    messagingSenderId: '776876278367',
    projectId: 'upda-8dccd',
    authDomain: 'upda-8dccd.firebaseapp.com',
    storageBucket: 'upda-8dccd.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2Q3FM3C1ycoR8qt3-lrZ82b5LaTnyBsk',
    appId: '1:776876278367:android:20cf691c32c115f0cf51ea',
    messagingSenderId: '776876278367',
    projectId: 'upda-8dccd',
    storageBucket: 'upda-8dccd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4FZHMJXutsvHOw4N7I1B1_GXGVR4w6oo',
    appId: '1:776876278367:ios:7760e6adf6461d8ecf51ea',
    messagingSenderId: '776876278367',
    projectId: 'upda-8dccd',
    storageBucket: 'upda-8dccd.firebasestorage.app',
    iosBundleId: 'com.n3t.upda3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4FZHMJXutsvHOw4N7I1B1_GXGVR4w6oo',
    appId: '1:776876278367:ios:7760e6adf6461d8ecf51ea',
    messagingSenderId: '776876278367',
    projectId: 'upda-8dccd',
    storageBucket: 'upda-8dccd.firebasestorage.app',
    iosBundleId: 'com.n3t.upda3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTvT_UAf_wGiY6mTjN_DvJg4x562ZlN9I',
    appId: '1:776876278367:web:5d6b24456c255b07cf51ea',
    messagingSenderId: '776876278367',
    projectId: 'upda-8dccd',
    authDomain: 'upda-8dccd.firebaseapp.com',
    storageBucket: 'upda-8dccd.firebasestorage.app',
  );
}
