// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1AVioeogsnSYq8hBB_gMhcRnkV8gtSDo',
    appId: '1:693290122798:web:6ee30360210926eba469bf',
    messagingSenderId: '693290122798',
    projectId: 'flutter-rpg-97fad',
    authDomain: 'flutter-rpg-97fad.firebaseapp.com',
    storageBucket: 'flutter-rpg-97fad.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-vHaSvq1OSMnEntM2uSdRheqkJ2ZwQXw',
    appId: '1:693290122798:android:72b2ecc732093c73a469bf',
    messagingSenderId: '693290122798',
    projectId: 'flutter-rpg-97fad',
    storageBucket: 'flutter-rpg-97fad.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvHg3EqVRm0kONcZWOAToCa3eToJihnhs',
    appId: '1:693290122798:ios:d461bd6a6e5d7116a469bf',
    messagingSenderId: '693290122798',
    projectId: 'flutter-rpg-97fad',
    storageBucket: 'flutter-rpg-97fad.firebasestorage.app',
    iosBundleId: 'com.n3t.upda3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvHg3EqVRm0kONcZWOAToCa3eToJihnhs',
    appId: '1:693290122798:ios:d461bd6a6e5d7116a469bf',
    messagingSenderId: '693290122798',
    projectId: 'flutter-rpg-97fad',
    storageBucket: 'flutter-rpg-97fad.firebasestorage.app',
    iosBundleId: 'com.n3t.upda3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD1AVioeogsnSYq8hBB_gMhcRnkV8gtSDo',
    appId: '1:693290122798:web:85a743c56af93e72a469bf',
    messagingSenderId: '693290122798',
    projectId: 'flutter-rpg-97fad',
    authDomain: 'flutter-rpg-97fad.firebaseapp.com',
    storageBucket: 'flutter-rpg-97fad.firebasestorage.app',
  );
}
